version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        networks:
            - mynetwork

    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run dev
        working_dir: /app
        volumes:
            - ./resources/js:/app/resources/js
        networks:
            - mynetwork

networks:
    mynetwork:
        driver: bridge
